service:
  name: any

custom:
  defaultStage: development
  defaultEnvironment: development

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-offline

package:
  excludeDevDependencies: false
  individually: true
  include:
    - '!./**'
  exclude:
    - './**'

functions:
  one:
    description: Print hello world
    memorySize: 1024
    timeout: 10
    handler: handlers/1.default
    package:
      include:
        - handlers/1.**

  two:
    description: Print hello world
    memorySize: 1024
    timeout: 10
    handler: handlers/1.default
    package:
      include:
        - handlers/1.**

  three:
    description: Print hello world
    memorySize: 1024
    timeout: 10
    handler: handlers/1.default
    package:
      include:
        - handlers/1.**

  four:
    description: Print hello world
    memorySize: 1024
    timeout: 10
    handler: handlers/1.default
    package:
      include:
        - handlers/1.**

  five:
    description: Print hello world
    memorySize: 1024
    timeout: 10
    handler: handlers/1.default
    package:
      include:
        - handlers/1.**
  
  six:
    description: Print hello world
    memorySize: 1024
    timeout: 10
    handler: handlers/1.default
    package:
      include:
        - handlers/1.**
